"""Render theme.css from theme.json, the Claude Design system exported from claude.ai/design."""
from pathlib import Path
import json

HERE = Path(__file__).resolve().parent
HAIRLINE = 0.12
ACCENT_INK = 0.35


def mix(base, toward, amount):
    channels = (round(int(base[at:at + 2], 16) * (1 - amount) + int(toward[at:at + 2], 16) * amount) for at in (1, 3, 5))
    return "#{:02x}{:02x}{:02x}".format(*channels)


def compute_tokens(theme):
    palette = theme["palette"]
    fonts = theme["fonts"]
    return {
        "--ds-name": f'"{theme["name"]}"',
        "--ds-bg": palette["bg"],
        "--ds-surface": palette["surface"],
        "--ds-text": palette["text"],
        "--ds-accent": palette["accent"],
        "--ds-accent-2": palette["accent2"],
        "--ds-accent-ink": mix(palette["accent"], palette["text"], ACCENT_INK),
        "--ds-hairline": mix(palette["surface"], palette["text"], HAIRLINE),
        "--ds-radius": f'{theme["radius"]}px',
        "--ds-density": str(theme["density"]),
        "--ds-heading-weight": str(fonts.get("headingWeight", 600)),
        "--ds-layout": theme["layoutStyle"],
        "--ds-dividers": theme.get("dividers", "none"),
        "--ds-image": theme["imageTreatment"],
        "--ds-color-use": theme.get("colorUse", "fill"),
        "--ds-button": theme.get("buttonStyle", "solid"),
    }


def render(theme):
    lines = [
        f'/* Generated by theme.py from theme.json, the Claude Design system "{theme["name"]}".',
        "   Every value below is the design system's; edit theme.json and regenerate, never this file.",
        "   check_site.py fails the build when the two disagree. course.css is the only consumer.",
        "",
        f"   Two values are derived rather than exported: --ds-hairline is the surface {HAIRLINE:.0%} of the",
        f"   way to the text, and --ds-accent-ink is the accent {ACCENT_INK:.0%} of the way there, dark",
        "   enough to carry link and heading text that the raw accent is too pale for.",
        "",
        "   Type is deliberately NOT taken from the design system. theme.json names a display and a",
        "   body face; both are ignored. The course is set in Roboto, which is the viewer's own label",
        "   font, so the documentation and the running app read as one thing. Only the heading WEIGHT",
        "   is the system's. mkdocs.yml keeps `font: false`; fonts/ holds the committed file.",
        "",
        "   Switching systems is one export: pull another project's theme.json from claude.ai/design",
        "   into this directory, run theme.py, and refetch the faces it names with fonts/fetch.sh. */",
        ":root {",
    ]
    for name, value in compute_tokens(theme).items():
        lines.append(f"  {name}: {value};")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main():
    theme = json.loads((HERE / "theme.json").read_text())
    (HERE / "theme.css").write_text(render(theme))


if __name__ == "__main__":
    main()

# description: rewrite theme.css from the design system exported in theme.json.
# directory: cd ~/code/code_cpp/wood_research/session/session_viewer
# run: python3 docs/stylesheets/theme.py
