vars: { d2-config: { layout-engine: elk; pad: 20; theme-id: 0 } }
style: { fill: "#ffffff" }
direction: down
a: "Normalized screen point"
b: "Undo scale and rotation"
c: "Add camera centre"
a -> b -> c
