vars: { d2-config: { layout-engine: elk; pad: 20; theme-id: 0 } }
style: { fill: "#ffffff" }
direction: down
a: "Action"
b: "Editor.apply"
c: "Change.Scene: display changed"
d: "Change.View: view changed"
a -> b
b -> c
b -> d
