vars: {
  d2-config: {
    layout-engine: elk
    pad: 20
    theme-id: 0
  }
}
style.fill: "#ffffff"
direction: down
start: Clock before work
operation: Original result
end: Clock after work
metadata: Valid completed metadata
return: Return original result
start -> operation
operation -> end
end -> metadata
metadata -> return
