vars: { d2-config: { layout-engine: elk; pad: 20; theme-id: 0 } }
style: { fill: "#ffffff" }
direction: down
a: "Pointer press"
b: "One active Drag"
c: "Matching pointer movement"
d: "Relative Motion"
a -> b -> c -> d
