                    "example face colors" => Action::AddColours(crate::colour::Mode::Faces),
                    "example sharp" => Action::AddNormals(crate::normal_example::Mode::Sharp),
                    "example smooth" => Action::AddNormals(crate::normal_example::Mode::Smooth),
                    "example winding" => Action::AddNormals(crate::normal_example::Mode::Winding),
                    "view normals on" => Action::NormalView(true),
                    "view normals off" => Action::NormalView(false),