    r#box,                   // register:box
    sphere,                  // register:sphere
    cylinder,                // register:cylinder
    cone,                    // register:cone
    pyramid,                 // register:pyramid
    torus,                   // register:torus
    block_with_hole,         // register:block_with_hole
    tetrahedron,             // register:tetrahedron
    octahedron,              // register:octahedron
    dodecahedron,            // register:dodecahedron
    icosahedron,             // register:icosahedron
    quad_sphere,             // register:quad_sphere
    capsule,                 // register:capsule
