    nurbs_curve_circle,      // register:nurbs_curve_circle
    nurbs_curve_ellipse,     // register:nurbs_curve_ellipse
    nurbs_curve_arc,         // register:nurbs_curve_arc
    nurbs_curve_parabola,    // register:nurbs_curve_parabola
    loft,                    // register:loft
    extrude,                 // register:extrude
    nurbs_surface_loft,      // register:nurbs_surface_loft
    nurbs_surface_network,   // register:nurbs_surface_network
    nurbs_surface_revolve,   // register:nurbs_surface_revolve
    nurbs_surface_4_points,  // register:nurbs_surface_4_points
    nurbs_surface_sweep1,    // register:nurbs_surface_sweep1
    nurbs_surface_sweep2,    // register:nurbs_surface_sweep2
