"""Expand lesson directives into exact code steps taken from the verified patch series.

A lesson is maintained Markdown. Its code never lives in the Markdown: a directive names a
step and a file, and this module renders the change as CURRENT / REPLACE WITH, ADD BELOW or
NEW FILE blocks cut from the patch that the checkpoint verification already proved. The audit
replays every lesson literally, the way a reader types it, and requires the result to hash to
the recorded checkpoint.

Directives (HTML comments, one per line):

    <!-- file: NN path [type|copy] [hunks=1-3] [lines=A-B] [whole] -->
    <!-- listing: NN path -->          complete file at step NN, READ ONLY
    <!-- supplied: NN -->              tooling files copied, never typed
    <!-- tree: NN prefix -->           file tree at step NN, new/changed marked
    <!-- check: NN -->                 a cargo check point measured by compile_points.py
    <!-- checkpoint: NN -->            the end-of-lesson build/run commands
"""
from pathlib import Path
import argparse
import hashlib
import importlib.util
import json
import os
import re
import shutil
import sys
import tempfile

HERE = Path(__file__).resolve().parent
SPEC = importlib.util.spec_from_file_location("course_replay", HERE / "reconstruction/replay.py")
REPLAY = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(REPLAY)

LANGUAGES = {".rs": "rust", ".wgsl": "wgsl", ".toml": "toml", ".lock": "toml",
             ".html": "html", ".css": "css", ".js": "javascript", ".cjs": "javascript",
             ".py": "python", ".sh": "bash", ".json": "json", ".yaml": "yaml",
             ".yml": "yaml", ".cpp": "cpp", ".h": "cpp", ".md": "markdown"}
LABELS = {"type": "TYPE THIS", "copy": "COPY", "read": "READ ONLY"}
COLLAPSE_COPY_LINES = 80
DIRECTIVE = re.compile(r"^<!-- (file|listing|supplied|tree|check|checkpoint): (\d\d[a-z]?)(.*?) -->$", re.MULTILINE)


def supplied(name):
    """Tooling the reader copies as a whole: tests, examples, parity ports, generated bytes."""
    return (name.endswith("Cargo.lock") or "/generated/" in name
            or name.startswith(("session_cpp/", "session_py/", "bash/"))
            or "/tests/" in name or "/examples/" in name or "_test." in name
            or "/selftest" in name or name.endswith("/text_quality.rs")
            or name.endswith((".gitignore", ".gitkeep", ".json")))


def default_label(name):
    """Viewer and kernel logic is typed; pages, fixtures and manifests are copied."""
    if name.endswith((".rs", ".wgsl")) and "/src/" in name and "fixture" not in name:
        return "type"
    return "copy"


def language(name):
    return LANGUAGES.get(Path(name).suffix, "text")


def short(name):
    """Show viewer paths from the crate root; sibling packages keep their prefix."""
    return name.removeprefix("session_viewer/")


def fence(name, text, title=None):
    """Explicit lexer and a fence longer than any fence inside the source."""
    length = max([3] + [len(run) + 1 for run in re.findall(r"`{3,}", text)])
    ticks = "`" * length
    head = f'{ticks}{language(name)}'
    if title:
        head += f' title="{title}"'
    body = text if text.endswith("\n") else text + "\n"
    return f"{head}\n{body}{ticks}\n"


class Hunk:
    """One unified-diff hunk as old and new line lists."""

    def __init__(self, header):
        self.header = header
        self.lines = []

    @property
    def old(self):
        return [line[1:] for line in self.lines if line[0] in " -"]

    @property
    def new(self):
        return [line[1:] for line in self.lines if line[0] in " +"]

    @property
    def added(self):
        return [line[1:] for line in self.lines if line[0] == "+"]

    @property
    def removed(self):
        return [line[1:] for line in self.lines if line[0] == "-"]

    def leading(self):
        count = 0
        for line in self.lines:
            if line[0] != " ":
                break
            count += 1
        return count

    def trailing(self):
        count = 0
        for line in reversed(self.lines):
            if line[0] != " ":
                break
            count += 1
        return count


class Change:
    """A file's change in one step: kind, hunks and both complete texts."""

    def __init__(self, name):
        self.name = name
        self.kind = "modify"
        self.hunks = []
        self.old_text = None
        self.new_text = None


def parse_patch(text):
    """Read every file section of a git patch into Change records with hunks."""
    changes = {}
    current = None
    hunk = None
    for line in text.split("\n"):
        if line.startswith("diff --git "):
            name = line.split(" b/", 1)[1]
            current = Change(name)
            changes[name] = current
            hunk = None
        elif current is None:
            continue
        elif line.startswith("new file mode"):
            current.kind = "create"
        elif line.startswith("deleted file mode"):
            current.kind = "delete"
        elif line.startswith("@@"):
            hunk = Hunk(line)
            current.hunks.append(hunk)
        elif hunk is not None and line and line[0] in " +-":
            hunk.lines.append(line)
        elif hunk is not None and line.startswith("\\ No newline"):
            continue
    return changes


class Step:
    """A verified checkpoint: its changes, complete post-state files and supplied inventory."""

    def __init__(self, record, changes, texts, previous_texts):
        self.record = record
        self.id = record["id"]
        self.changes = changes
        self.texts = texts
        self.previous_texts = previous_texts
        self.assets = record.get("assets", [])

    def supplied_files(self):
        return sorted(name for name, change in self.changes.items()
                      if supplied(name) and change.kind != "delete")


def build_steps(workspace_root):
    """Apply the series in a disposable workspace and retain every changed file's text."""
    REPLAY.print = lambda *args, **kwargs: None
    series = REPLAY.read_json(HERE / "reconstruction/series.json")
    workspace = workspace_root / "workspace"
    REPLAY.initialize(workspace)
    REPLAY.run(["git", "init", "--quiet"], workspace, dict(os.environ), workspace_root / "logs/init.log")
    steps = []
    texts = {}
    for record in series["steps"]:
        patch = (HERE / "reconstruction" / record["patch"]).read_text()
        changes = parse_patch(patch)
        previous_texts = {}
        for name, change in changes.items():
            path = workspace / name
            previous_texts[name] = path.read_text() if path.is_file() else None
            change.old_text = previous_texts[name]
        REPLAY.apply_step(workspace, record, dict(os.environ), workspace_root / "logs" / record["id"])
        texts = {name: None for name in texts}
        for name in record["files"]:
            texts[name] = REPLAY.digest(workspace / name)
        for name, change in changes.items():
            path = workspace / name
            change.new_text = path.read_text() if path.is_file() else None
        step = Step(record, changes, dict(record["files"]), previous_texts)
        step.workspace = workspace
        step.file_texts = {name: change.new_text for name, change in changes.items()}
        steps.append(step)
    return series, steps, workspace


def parse_args_text(rest):
    """Read the tokens after `kind: NN` into a path plus options."""
    tokens = rest.split()
    options = {"path": None, "label": None, "hunks": None, "lines": None, "whole": False}
    for token in tokens:
        if token in LABELS:
            options["label"] = token
        elif token == "whole":
            options["whole"] = True
        elif token.startswith("hunks="):
            options["hunks"] = parse_range(token[6:])
        elif token.startswith("lines="):
            first, last = token[6:].split("-")
            options["lines"] = (int(first), int(last))
        elif options["path"] is None:
            options["path"] = token
        else:
            raise ValueError(f"unexpected directive token: {token}")
    return options


def parse_range(text):
    numbers = set()
    for part in text.split(","):
        if "-" in part:
            first, last = part.split("-")
            numbers.update(range(int(first), int(last) + 1))
        else:
            numbers.add(int(part))
    return sorted(numbers)


def unique(block, haystack):
    """One occurrence, and at least one non-blank line so the reader can find it."""
    return bool(block.strip()) and haystack.count(block) == 1


def old_start(hunk):
    """The 1-based first old line of a hunk, from its @@ header."""
    match = re.match(r"@@ -(\d+)", hunk.header)
    return int(match.group(1)) if match else 1


def trim_hunk(hunk, old_text, current_text=None):
    """Keep the least context that still names one place in the file the reader edits.

    Context is first trimmed to one line each side, widened back through the hunk's own
    context, then extended with neighbouring lines of the file itself when even the full
    hunk context is ambiguous (repeated blank lines, repeated table headers).
    """
    haystack = old_text if current_text is None else current_text
    lead, trail = hunk.leading(), hunk.trailing()
    body = hunk.lines[lead:len(hunk.lines) - trail] if trail else hunk.lines[lead:]
    file_lines = old_text.split("\n") if old_text is not None else []
    start = old_start(hunk)
    old_count = len(hunk.old)
    keep_lead = min(1, lead)
    keep_trail = min(1, trail)
    extra_before = 0
    extra_after = 0

    def blocks(kl, kt, before, after):
        head = hunk.lines[lead - kl:lead]
        tail = hunk.lines[len(hunk.lines) - trail:len(hunk.lines) - trail + kt] if trail else []
        outer_head = [" " + line for line in file_lines[max(0, start - 1 - before):start - 1]]
        outer_tail = [" " + line for line in file_lines[start - 1 + old_count:start - 1 + old_count + after]]
        chosen = outer_head + head + body + tail + outer_tail
        old = "\n".join(line[1:] for line in chosen if line[0] in " -")
        new = "\n".join(line[1:] for line in chosen if line[0] in " +")
        return old, new, outer_head + head, tail + outer_tail

    old, new, head, tail = blocks(keep_lead, keep_trail, extra_before, extra_after)
    while not unique(old, haystack):
        if keep_lead < lead:
            keep_lead += 1
        elif keep_trail < trail:
            keep_trail += 1
        elif extra_before < 8 and start - 1 - extra_before > 0:
            extra_before += 1
        elif extra_after < 8 and start - 1 + old_count + extra_after < len(file_lines):
            extra_after += 1
        else:
            break
        old, new, head, tail = blocks(keep_lead, keep_trail, extra_before, extra_after)
    return old, new, [line[1:] for line in head], [line[1:] for line in tail]


def contiguous_insertion(hunk):
    """True when the hunk only adds one unbroken run of lines (no removed or interior context)."""
    body = hunk.lines[hunk.leading():len(hunk.lines) - hunk.trailing()]
    return bool(body) and all(line[0] == "+" for line in body)


def render_hunk(name, hunk, old_text, current_text):
    """CURRENT / REPLACE WITH for an edit; an anchored ADD BELOW for a pure insertion.

    Uniqueness is judged against `current_text`, the file as the reader has it after the
    earlier instructions of the same lesson, not only against the checkpoint's old file.
    """
    old, new, head, tail = trim_hunk(hunk, old_text, current_text)
    if contiguous_insertion(hunk):
        if head:
            anchor = "\n".join(head)
            if unique(anchor, current_text):
                return (f"**CURRENT**\n\n{fence(name, anchor)}\n**ADD BELOW**\n\n"
                        f"{fence(name, chr(10).join(hunk.added))}")
        if tail:
            anchor = "\n".join(tail)
            if unique(anchor, current_text):
                return (f"**CURRENT**\n\n{fence(name, anchor)}\n**ADD ABOVE**\n\n"
                        f"{fence(name, chr(10).join(hunk.added))}")
    if not old.strip():
        raise ValueError(f"hunk without a locatable CURRENT block in {name}: {hunk.header}")
    if not new.strip():
        return f"**CURRENT**\n\n{fence(name, old)}\n**DELETE** these lines.\n"
    return f"**CURRENT**\n\n{fence(name, old)}\n**REPLACE WITH**\n\n{fence(name, new)}"


def apply_hunk(name, hunk, old_text, current_text):
    """Apply one rendered instruction to the reader's working text, by search."""
    old, new, head, tail = trim_hunk(hunk, old_text, current_text)
    if contiguous_insertion(hunk):
        added = "\n".join(hunk.added)
        if head:
            anchor = "\n".join(head)
            if unique(anchor, current_text):
                return current_text.replace(anchor, anchor + "\n" + added, 1)
        if tail:
            anchor = "\n".join(tail)
            if unique(anchor, current_text):
                return current_text.replace(anchor, added + "\n" + anchor, 1)
    if not unique(old, current_text):
        raise ValueError(f"CURRENT block is not unique while replaying {name}:\n{old}")
    return current_text.replace(old, new, 1)


def finish_newline(text, reference):
    """Editors keep one final newline; make the replayed text agree with the checkpoint file."""
    if reference is None:
        return text
    if reference.endswith("\n") and not text.endswith("\n"):
        return text + "\n"
    if not reference.endswith("\n") and text.endswith("\n"):
        return text.rstrip("\n")
    return text


def collapsible(label, name, text, download):
    """Long copied files fold away; the download is the exact bytes."""
    lines = text.count("\n")
    title = f'{label} · `{short(name)}` · {lines} lines · [download]({download}){{ download="{Path(name).name}" }}'
    body = fence(name, text)
    return f'??? note "{title}"\n\n' + "\n".join("    " + line for line in body.split("\n")) + "\n"


class Renderer:
    """Expand directives for one lesson against the verified series."""

    def __init__(self, steps, download_base, points):
        self.steps = {step.id: step for step in steps}
        self.download_base = download_base
        self.points = points
        self.used = {}
        self.order = {}
        self.working = {}

    def note_use(self, step_id, name, hunks=None, lines=None):
        used = self.used.setdefault(step_id, {}).setdefault(name, {"hunks": [], "lines": [], "whole": 0})
        if hunks is not None:
            used["hunks"].extend(hunks)
        if lines is not None:
            used["lines"].append(lines)
        if hunks is None and lines is None:
            used["whole"] += 1
        self.order.setdefault(step_id, []).append(("file", name))

    def download(self, step_id, name):
        return f"{self.download_base}/{step_id}/raw/{name.replace('/', '--')}.txt"

    def finished(self, step_id, name):
        """A link to the file as it stands when this lesson is complete."""
        return f'[finished file ↓]({self.download(step_id, name)}){{ download="{Path(name).name}" }}'


    def file(self, step_id, options):
        step = self.steps[step_id]
        name = options["path"]
        change = step.changes.get(name)
        if change is None:
            raise ValueError(f"step {step_id} does not change {name}")
        label = LABELS[options["label"] or default_label(name)]
        title = short(name)
        if change.kind == "delete":
            self.note_use(step_id, name)
            return f"**File:** `{name}` · **DELETE** this file.\n"
        if change.kind == "create" or options["whole"]:
            text = change.new_text
            verb = "NEW FILE" if change.kind == "create" else "REPLACE THE WHOLE FILE WITH"
            if options["lines"]:
                first, last = options["lines"]
                all_lines = text.split("\n")
                if all_lines and all_lines[-1] == "":
                    all_lines.pop()
                chunk = "\n".join(all_lines[first - 1:last]) + "\n"
                if first > 1:
                    verb = "ADD BELOW (append at the end of the file)"
                self.note_use(step_id, name, lines=(first, last))
                head = f"**File:** `{name}` · **{verb}** · lines {first}–{last} of {len(all_lines)} · {label} · {self.finished(step_id, name)}\n\n"
                return head + fence(name, chunk, title)
            self.note_use(step_id, name)
            head = f"**File:** `{name}` · **{verb}** · {label} · {self.finished(step_id, name)}\n\n"
            if label == "COPY" and text.count("\n") > COLLAPSE_COPY_LINES:
                return head + collapsible(verb, name, text, self.download(step_id, name))
            return head + fence(name, text, title)
        hunks = options["hunks"] or list(range(1, len(change.hunks) + 1))
        for number in hunks:
            if number < 1 or number > len(change.hunks):
                raise ValueError(f"{name} at {step_id} has {len(change.hunks)} hunks, not {number}")
        self.note_use(step_id, name, hunks=hunks)
        parts = [f"**File:** `{name}` · **EDIT** · {label} · {self.finished(step_id, name)}\n"]
        current = self.working.get((step_id, name), change.old_text)
        for number in hunks:
            hunk = change.hunks[number - 1]
            parts.append(render_hunk(name, hunk, change.old_text, current))
            current = apply_hunk(name, hunk, change.old_text, current)
        self.working[(step_id, name)] = current
        return "\n".join(parts)

    def listing(self, step_id, options):
        step = self.steps[step_id]
        name = options["path"]
        text = step_text(step, name)
        title = f'READ ONLY · `{short(name)}` at checkpoint {step_id} · {text.count(chr(10))} lines'
        body = fence(name, text)
        return f'??? example "{title}"\n\n' + "\n".join("    " + line for line in body.split("\n")) + "\n"

    def supplied(self, step_id):
        step = self.steps[step_id]
        names = step.supplied_files()
        self.order.setdefault(step_id, []).append(("supplied", None))
        if not names and not step.assets:
            return ""
        lines = ["**Supplied files** · COPY · tooling and fixtures this checkpoint needs but the "
                 "course does not teach. One command installs them all:\n",
                 "```sh\npython3 \"$COURSE_REPO/docs/reconstruction/replay.py\" "
                 f"--output \"$COURSE_WORK\" --through {step_id} --copy-supplied\n```\n"]
        for name in names:
            lines.append(f"- [`{name}`]({self.download(step_id, name)}){{ download=\"{Path(name).name}\" }}")
        for asset in step.assets:
            lines.append(f"- `{asset['target']}` (binary, SHA-256 `{asset['sha256'][:12]}…`)")
        return "\n".join(lines) + "\n"

    def tree(self, step_id, options):
        step = self.steps[step_id]
        prefix = options["path"] or "session_viewer/src"
        names = sorted(name for name in step.texts if name.startswith(prefix + "/") and not supplied(name))
        marks = {}
        for name, change in step.changes.items():
            marks[name] = {"create": "+", "delete": "-", "modify": "~"}[change.kind]
        root = {}
        for name in names:
            node = root
            for part in name[len(prefix) + 1:].split("/"):
                node = node.setdefault(part, {})
            node["\0"] = marks.get(name, " ")
        out = [prefix + "/"]

        def walk(node, indent):
            entries = sorted((key, value) for key, value in node.items() if key != "\0")
            entries.sort(key=lambda item: (not bool({k for k in item[1] if k != "\0"}), item[0]))
            for index, (key, value) in enumerate(entries):
                last = index == len(entries) - 1
                children = {k for k in value if k != "\0"}
                mark = value.get("\0", " ") if not children else " "
                out.append(f"{indent}{'└── ' if last else '├── '}{key}{'/' if children else ''}"
                           f"{'  ' + mark if mark.strip() else ''}")
                if children:
                    walk(value, indent + ("    " if last else "│   "))

        walk(root, "")
        legend = "`+` new in this lesson · `~` changed in this lesson"
        return "```text\n" + "\n".join(out) + "\n```\n\n" + legend + "\n"

    def check(self, step_id):
        position = len(self.order.get(step_id, []))
        self.order.setdefault(step_id, []).append(("check", position))
        recorded = self.points.get(step_id, {}).get(str(position))
        state = "passes here" if recorded == "ok" else "UNMEASURED"
        return ("```sh\ncargo check --locked --lib\n```\n\n"
                f"Expected: no errors (measured: {state}).\n")

    def checkpoint(self, step_id):
        self.order.setdefault(step_id, []).append(("checkpoint", None))
        # Raw HTML is not rewritten by MkDocs: from a directory URL the lesson page sits one level deeper.
        banner = (f'<div class="source-banner"><strong>Source at this step.</strong> '
                  f'<a href="../{self.download_base}/{step_id}/">Every file at checkpoint {step_id}</a>, each downloadable '
                  f'exactly as the checkpoint has it. The finished viewer is on '
                  f'<a href="{GITHUB_SOURCE}">GitHub</a>.</div>\n\n')
        return banner + ("```sh\ncd \"$COURSE_WORK/session_viewer\"\ncargo check --locked --lib\n"
                "trunk serve --port 8780\n```\n\n"
                "Open <http://localhost:8780/?data=off&inspect=1>. Stop the server with Ctrl+C before the next lesson.\n")

    def expand(self, markdown):
        def replace(match):
            kind, step_id, rest = match.groups()
            if step_id not in self.steps:
                raise ValueError(f"unknown step {step_id}")
            options = parse_args_text(rest)
            if kind == "file":
                return self.file(step_id, options)
            if kind == "listing":
                return self.listing(step_id, options)
            if kind == "supplied":
                return self.supplied(step_id)
            if kind == "tree":
                return self.tree(step_id, options)
            if kind == "check":
                return self.check(step_id)
            return self.checkpoint(step_id)
        return DIRECTIVE.sub(replace, markdown)


def step_text(step, name):
    """The complete text of a file at a checkpoint, from the shared reconstruction workspace."""
    path = step.workspace_snapshot / name
    return path.read_text()


def lesson_files():
    return sorted(HERE.glob("[0-9][0-9]*-*.md"))


def lesson_for(step_id):
    matches = [path for path in lesson_files() if path.name.startswith(step_id + "-")]
    if len(matches) != 1:
        raise ValueError(f"expected one lesson for step {step_id}, found {matches}")
    return matches[0]


def snapshot_steps(root):
    """Reconstruct once and keep a per-step copy of every changed file for listings/replay."""
    series, steps, workspace = build_steps(root)
    # A file's text at step k is its newest change at or before k; before its first change
    # it is the pinned base text; files no patch touches are the same at every step.
    first_old = {}
    for step in steps:
        for name, change in step.changes.items():
            first_old.setdefault(name, change.old_text)
    latest = {}
    for step in steps:
        for name, change in step.changes.items():
            latest[name] = change.new_text
        snapshot = root / "snapshots" / step.id
        snapshot.mkdir(parents=True, exist_ok=True)
        step.workspace_snapshot = snapshot
        for name in step.texts:
            target = snapshot / name
            if name in latest:
                data = latest[name]
            elif name in first_old:
                data = first_old[name]
            else:
                source = workspace / name
                data = source.read_bytes() if source.is_file() else None
            if data is None:
                continue
            target.parent.mkdir(parents=True, exist_ok=True)
            if isinstance(data, str):
                target.write_text(data)
            else:
                target.write_bytes(data)
    return series, steps


def replay_lesson(step, markdown, previous_snapshot):
    """Follow the lesson's directives literally and return the resulting changed-file texts."""
    files = {}
    for name in step.changes:
        source = previous_snapshot / name
        if source.is_file():
            files[name] = source.read_text()
    for match in DIRECTIVE.finditer(markdown):
        kind, step_id, rest = match.groups()
        if step_id != step.id or kind not in ("file", "supplied"):
            continue
        if kind == "supplied":
            for name in step.supplied_files():
                files[name] = step.changes[name].new_text
            continue
        options = parse_args_text(rest)
        name = options["path"]
        change = step.changes[name]
        if change.kind == "delete":
            files.pop(name, None)
        elif change.kind == "create" or options["whole"]:
            if options["lines"]:
                first, last = options["lines"]
                all_lines = change.new_text.split("\n")
                if all_lines and all_lines[-1] == "":
                    all_lines.pop()
                chunk = "\n".join(all_lines[first - 1:last]) + "\n"
                files[name] = (files.get(name, "") if first > 1 else "") + chunk
            else:
                files[name] = change.new_text
        else:
            hunks = options["hunks"] or list(range(1, len(change.hunks) + 1))
            current = files[name]
            for number in hunks:
                current = apply_hunk(name, change.hunks[number - 1], change.old_text, current)
            files[name] = finish_newline(current, change.new_text)
    return files


def audit(root, points, only=None):
    """Every change is taught or supplied exactly once, and typing the lesson yields the checkpoint."""
    series, steps = snapshot_steps(root)
    errors = []
    previous = None
    for step in steps:
        if only and step.id not in only:
            previous = step.workspace_snapshot
            continue
        lesson = lesson_for(step.id)
        markdown = lesson.read_text()
        renderer = Renderer(steps, "lessons", points)
        try:
            renderer.expand(markdown)
        except ValueError as error:
            errors.append(f"{lesson.name}: {error}")
            previous = step.workspace_snapshot
            continue
        used = renderer.used.get(step.id, {})
        for name, change in sorted(step.changes.items()):
            record = used.get(name)
            if supplied(name) and record is None:
                if change.kind != "delete" and not any(kind == "supplied" for kind, _ in renderer.order.get(step.id, [])):
                    errors.append(f"{lesson.name}: supplied file {name} needs a <!-- supplied: {step.id} --> directive")
                continue
            if record is None:
                errors.append(f"{lesson.name}: orphaned change {name} ({change.kind}, {len(change.hunks)} hunks)")
                continue
            if change.kind == "modify" and record["whole"] == 0 and not record["lines"]:
                expected = list(range(1, len(change.hunks) + 1))
                if sorted(record["hunks"]) != expected:
                    errors.append(f"{lesson.name}: {name} hunks used {sorted(record['hunks'])}, expected {expected}")
            elif record["lines"]:
                total = change.new_text.rstrip("\n").count("\n") + 1
                covered = []
                for first, last in sorted(record["lines"]):
                    covered.extend(range(first, last + 1))
                if covered != list(range(1, total + 1)):
                    errors.append(f"{lesson.name}: {name} line ranges do not tile 1–{total} in order")
            elif record["whole"] != 1 and not record["lines"]:
                errors.append(f"{lesson.name}: {name} referenced {record['whole']} times")
        for kind, position in renderer.order.get(step.id, []):
            if kind == "check" and points.get(step.id, {}).get(str(position)) != "ok":
                errors.append(f"{lesson.name}: cargo check point at position {position} is not recorded as passing "
                              f"(run docs/reconstruction/compile_points.py --lesson {step.id})")
        if previous is not None or step.id == steps[0].id:
            try:
                base = previous if previous is not None else None
                files = replay_lesson(step, markdown, base) if base is not None else replay_lesson(step, markdown, root / "empty")
            except ValueError as error:
                errors.append(f"{lesson.name}: replay failed: {error}")
            else:
                for name, checksum in sorted(step.texts.items()):
                    if name in step.changes:
                        text = files.get(name)
                        actual = hashlib.sha256(text.encode()).hexdigest() if text is not None else None
                        if actual != checksum:
                            errors.append(f"{lesson.name}: typing the lesson does not reproduce {name}")
                for name in step.changes:
                    if step.changes[name].kind == "delete" and name in files:
                        errors.append(f"{lesson.name}: {name} should be deleted")
        previous = step.workspace_snapshot
    return errors


def load_points():
    path = HERE / "reconstruction/compile-points.json"
    return json.loads(path.read_text()) if path.is_file() else {}


def write_downloads(steps, output):
    """Exact bytes of every changed text file, for COPY links and supplied lists."""
    for step in steps:
        raw = output / step.id / "raw"
        raw.mkdir(parents=True, exist_ok=True)
        for name, change in step.changes.items():
            if change.new_text is None:
                continue
            (raw / (name.replace("/", "--") + ".txt")).write_text(change.new_text)


GITHUB_SOURCE = "https://github.com/petrasvestartas/session/tree/main/session_viewer"


def write_source_index(steps, output):
    """One page per checkpoint listing every file it contains, each linked to its exact bytes."""
    last_changed = {}
    for step in steps:
        for name, change in step.changes.items():
            if change.new_text is not None:
                last_changed[name] = step.id
            elif name in last_changed:
                del last_changed[name]
        lines = [f"# Source at checkpoint {step.id}", "",
                 f"Every file of the viewer as it stands at the end of lesson {step.id}. Each link downloads the exact "
                 "bytes the checkpoint hash was recorded from; files this lesson did not touch link to the checkpoint "
                 f"that last changed them. The finished production source is on [GitHub]({GITHUB_SOURCE}).", "",
                 "[Back to the course](../../docs/)", ""]
        for name in sorted(step.texts):
            origin = last_changed.get(name)
            if origin is None:
                continue
            target = f"raw/{name.replace('/', '--')}.txt" if origin == step.id else f"../{origin}/raw/{name.replace('/', '--')}.txt"
            mark = " · changed in this lesson" if origin == step.id else ""
            lines.append(f"- [`{name}`]({target}){{ download=\"{Path(name).name}\" }}{mark}")
        (output / step.id).mkdir(parents=True, exist_ok=True)
        (output / step.id / "index.md").write_text("\n".join(lines) + "\n")


STATE = {}


def on_pre_build(config):
    """MkDocs hook: reconstruct the verified series once per series/script revision."""
    source = Path(config["docs_dir"])
    output = source / "lessons"
    series_path = HERE / "reconstruction/series.json"
    key = hashlib.sha256(series_path.read_bytes() + Path(__file__).read_bytes()).hexdigest()
    cache = source.parent / "course-cache"
    stamp = cache / "manifest.json"
    if not (stamp.is_file() and json.loads(stamp.read_text()).get("key") == key):
        if cache.exists():
            shutil.rmtree(cache)
        if output.exists():
            shutil.rmtree(output)
        cache.mkdir(parents=True)
        (cache / "empty").mkdir()
        series, steps = snapshot_steps(cache)
        write_downloads(steps, output)
        stamp.write_text(json.dumps({"key": key, "production_tree": series["production_tree"]}) + "\n")
    else:
        series, steps = reload_steps(cache)
    write_source_index(steps, output)
    STATE["steps"] = steps
    STATE["points"] = load_points()


def reload_steps(cache):
    """Rebuild in-memory step records from the patches and the cached snapshots."""
    series = REPLAY.read_json(HERE / "reconstruction/series.json")
    steps = []
    previous = None
    for record in series["steps"]:
        changes = parse_patch((HERE / "reconstruction" / record["patch"]).read_text())
        snapshot = cache / "snapshots" / record["id"]
        for name, change in changes.items():
            path = snapshot / name
            change.new_text = path.read_text() if path.is_file() else None
            old = previous / name if previous is not None else None
            change.old_text = old.read_text() if old is not None and old.is_file() else None
        step = Step(record, changes, dict(record["files"]), {})
        step.workspace_snapshot = snapshot
        steps.append(step)
        previous = snapshot
    return series, steps


MERMAID_INIT = '%%{init: {"flowchart": {"useMaxWidth": false}, "themeVariables": {"primaryColor": "#ffffff", "primaryTextColor": "#111111", "primaryBorderColor": "#111111", "lineColor": "#ffffff", "secondaryColor": "#ffffff", "tertiaryColor": "#ffffff", "edgeLabelBackground": "#111111"}}}%%'


def mermaid_natural_size(markdown):
    """Every Mermaid block keeps its natural size (it scrolls instead of shrinking) and white nodes."""
    return re.sub(r"(?m)^```mermaid[ \t]*\n(?!%%\{init)", "```mermaid\n" + MERMAID_INIT + "\n", markdown)


def on_page_markdown(markdown, page, config, files):
    """Expand directives in maintained lesson pages."""
    markdown = mermaid_natural_size(markdown)
    if "steps" not in STATE or not DIRECTIVE.search(markdown):
        return markdown
    depth = page.file.src_path.count("/")
    base = "../" * depth + "lessons"
    renderer = Renderer(STATE["steps"], base, STATE["points"])
    return renderer.expand(markdown)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--audit", action="store_true", help="check coverage and replay every lesson")
    parser.add_argument("--render", type=Path, help="write expanded lessons to this directory")
    parser.add_argument("--lesson", action="append", help="audit only this step id (repeatable)")
    args = parser.parse_args()
    points = load_points()
    scratch = HERE.parent / "target/docs"
    scratch.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="course-audit-", dir=scratch) as temporary:
        root = Path(temporary)
        (root / "empty").mkdir()
        if args.render:
            series, steps = snapshot_steps(root)
            args.render.mkdir(parents=True, exist_ok=True)
            for step in steps:
                if args.lesson and step.id not in args.lesson:
                    continue
                renderer = Renderer(steps, "lessons", points)
                (args.render / lesson_for(step.id).name).write_text(renderer.expand(lesson_for(step.id).read_text()))
            print(f"rendered {len(steps)} lessons to {args.render}")
        if args.audit or not args.render:
            errors = audit(root, points, args.lesson)
            if errors:
                print("\n".join(errors))
                sys.exit(1)
            print("PASS: every lesson covers its checkpoint and replays to the recorded hashes")


if __name__ == "__main__":
    main()
