"""Render complete, verified lesson files for MkDocs without duplicating source in Git."""
from pathlib import Path
import hashlib
import importlib.util
import json
import os
import re
import shutil
import tempfile

HERE = Path(__file__).resolve().parent
SPEC = importlib.util.spec_from_file_location("course_replay", HERE / "reconstruction/replay.py")
REPLAY = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(REPLAY)

LANGUAGES = {".rs": "rust", ".wgsl": "wgsl", ".toml": "toml", ".lock": "toml",
             ".html": "html", ".css": "css", ".js": "javascript", ".cjs": "javascript",
             ".py": "python", ".sh": "bash", ".json": "json", ".yaml": "yaml",
             ".yml": "yaml", ".cpp": "cpp", ".h": "cpp", ".md": "markdown"}


def chapter_paths():
    """Use the unique numbered chapter names as the stable prose entry points."""
    return {path.name[:2]: path.name for path in HERE.glob("[0-9][0-9]-*.md")}


def file_order(name):
    """Put configuration and contracts before producers, rendering, wiring and test tools."""
    if "/src/" not in name:
        group = 0 if name.endswith((".toml", "Cargo.lock", "index.html")) else 8
    elif not name.startswith("session_viewer/"):
        group = 1
    elif "/shaders/" in name:
        group = 3
    elif "/app/walk/" in name:
        group = 2
    elif "/engine/" in name:
        group = 4
    elif name.endswith(("/lib.rs", "/state.rs")):
        group = 6
    else:
        group = 5
    if "/tests/" in name or "/examples/" in name or "_test." in name:
        group = 7
    return group, name


def slug(name):
    """Keep source-path punctuation out of routing while retaining an obvious filename."""
    return name.replace("/", "--") + ".md"


def raw_name(name):
    """Flatten source dot-directories so MkDocs copies every exact download as text."""
    return name.replace("/", "--") + ".txt"


def category(name):
    """Distinguish the viewer being taught from supplied fixtures and parity tools."""
    if name.endswith("Cargo.lock") or "/generated/" in name:
        return "COPY supplied dependency/generated bytes; do not transcribe these mechanically."
    if "/tests/" in name or "/examples/" in name or "_test." in name:
        return "COPY the complete verification tool, then read its assertions when checking this lesson."
    if name.startswith(("session_cpp/", "session_py/")):
        return "COPY the independent parity implementation; the lesson explains the shared contract in Rust."
    return "TYPE OR COPY the complete file. Read the lesson explanation before changing its behavior."


def listing(name, text):
    """Choose an explicit lexer and a fence longer than any fence inside the source."""
    language = LANGUAGES.get(Path(name).suffix, "text")
    length = max([3] + [len(run) + 1 for run in re.findall(r"`{3,}", text)])
    fence = "`" * length
    return f'{fence}{language} title="{name}"\n{text if text.endswith(chr(10)) else text + chr(10)}{fence}\n'


def render_step(workspace, step, previous, output, chapter):
    """Supply every changed text file in full, plus explicit removals and binary inputs."""
    destination = output / step["id"]
    destination.mkdir(parents=True)
    current = step["files"]
    changed = sorted((name for name in current if previous.get(name) != current[name]), key=file_order)
    deleted = sorted(set(previous) - set(current))
    binary = {asset["target"] for asset in step.get("assets", [])}
    pages = []
    table = [f'# {step["id"]} — Complete file changes\n',
             f'[Read the lesson](../../docs/{chapter}). Start from the previous checkpoint. '
             'Apply every listed file once, in the order below, then run the lesson checkpoint. '
             'There are no omitted imports or hidden patch-only additions.\n',
             'All paths below start at `$COURSE_WORK`, the directory containing `session_viewer` and `session_rust`. '
             '**Create** means a new file; **replace** means its entire contents. Leave unlisted files unchanged.\n',
             '| Order | Action | Complete file |\n|---|---|---|']
    for name in changed:
        if name in binary:
            continue
        source = REPLAY.safe_path(workspace, name)
        try:
            text = source.read_text()
        except UnicodeDecodeError as error:
            raise ValueError(f"binary asset missing from step inventory: {name}") from error
        action = "Replace" if name in previous else "Create"
        filename = slug(name)
        table.append(f'| {len(pages)+1} | {action} | [{name}]({filename}) |')
        pages.append((name, filename, text, action))
    if deleted:
        table += ['\n## Remove these obsolete files\n',
                  'Delete exactly these files from the teaching workspace. Their replacement belongs to this lesson.\n']
        table += [f'- `{name}`' for name in deleted]
    if binary:
        table += ['\n## Copy binary inputs\n',
                  'Fonts and protobuf fixtures are supplied bytes, not code to type. Run:\n',
                  '```sh\npython3 "$COURSE_REPO/docs/reconstruction/replay.py" '
                  f'--output "$COURSE_WORK" --through {step["id"]} --copy-assets\n```\n']
        table += [f'- `{asset["target"]}` — SHA-256 `{asset["sha256"]}`'
                  for asset in step["assets"]]
    table += [f'\n[Return to lesson {step["id"]}: build and run](../../docs/{chapter}#checkpoint)\n']
    (destination / "index.md").write_text("\n".join(table))
    for index, (name, filename, text, action) in enumerate(pages):
        # Raw files make long configuration and test tools convenient to copy exactly.
        raw = destination / "raw" / raw_name(name)
        raw.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(workspace / name, raw)
        body = [f'# {step["id"]} · {name}\n',
                f'[Lesson](../../docs/{chapter}) · [All edits](index.md) · '
                f'[Download exact file](raw/{raw_name(name)}){{ download="{Path(name).name}" }}\n',
                f'**File {index+1} of {len(pages)}. {action} `$COURSE_WORK/{name}` in full.**\n',
                category(name) + '\n',
                'Create parent directories when necessary. The copy button copies only code. '
                'Do not paste the filename, language marker or surrounding Markdown fence.\n',
                listing(name, text),
                f'Checksum of the downloadable file: `{current[name]}`.\n']
        if index + 1 < len(pages):
            following = pages[index+1]
            body += [f'**Next:** [{following[0]}]({following[1]}).\n']
        else:
            body += ['**Next:** finish any [listed removals/binary inputs](index.md), then '
                     f'[build and run the checkpoint](../../docs/{chapter}#checkpoint).\n']
        (destination / filename).write_text('\n'.join(body))
    return {"id": step["id"], "complete_text_files": len(pages), "deleted": deleted,
            "binary": sorted(binary), "patch_sha256": step["patch_sha256"]}


def on_pre_build(config):
    """MkDocs hook: reconstruct verified sources before MkDocs discovers lesson pages."""
    source = Path(config["docs_dir"])
    output = source / "lessons"
    series_path = HERE / "reconstruction/series.json"
    chapters = chapter_paths()
    key = hashlib.sha256(series_path.read_bytes() + Path(__file__).read_bytes()
                         + json.dumps(chapters, sort_keys=True).encode()).hexdigest()
    stamp = output / "manifest.json"
    if stamp.is_file() and json.loads(stamp.read_text()).get("key") == key:
        return
    # Only this hook's generated output is replaced; maintained docs and source are untouched.
    if output.exists():
        shutil.rmtree(output)
    output.mkdir(parents=True)
    series = REPLAY.read_json(series_path)
    reports = []
    with tempfile.TemporaryDirectory(prefix="course-listings-", dir=source.parent) as temporary:
        workspace = Path(temporary) / "workspace"
        REPLAY.initialize(workspace)
        previous = {path.relative_to(workspace).as_posix(): REPLAY.digest(path)
                    for path in workspace.rglob("*") if path.is_file()}
        # The build directory may live inside the user's Git checkout. Give this disposable
        # workspace its own root so git apply never interprets the enclosing repo's prefix.
        REPLAY.run(["git", "init", "--quiet"], workspace, dict(os.environ),
                   Path(temporary) / "logs/init.log")
        for step in series["steps"]:
            REPLAY.apply_step(workspace, step, dict(os.environ), Path(temporary) / "logs" / step["id"])
            reports.append(render_step(workspace, step, previous, output, chapters[step["id"]]))
            previous = step["files"]
    stamp.write_text(json.dumps({"key": key, "production_tree": series["production_tree"],
                                 "steps": reports}, indent=2) + '\n')


def on_page_markdown(markdown, page, config, files):
    """Inline an explicitly requested small file from the same verified lesson bytes."""
    def include(match):
        step, name = match.groups()
        path = REPLAY.safe_path(Path(config["docs_dir"]) / "lessons" / step / "raw", raw_name(name))
        return listing(name, path.read_text())
    return re.sub(r"<!-- include-code: (\d\d) ([\w./-]+) -->", include, markdown)
