name: Build Session Rust

on:
  push:
    branches: [ main, develop ]
    paths: [ 'session_rust/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'session_rust/**' ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust: [stable, beta, nightly]

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust }}

    - name: Cache cargo registry
      uses: actions/cache@v3
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

    - name: Cache cargo index
      uses: actions/cache@v3
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}

    - name: Cache cargo build
      uses: actions/cache@v3
      with:
        path: session_rust/target
        key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}

    - name: Check formatting
      working-directory: ./session_rust
      run: cargo fmt --all -- --check

    - name: Run clippy
      working-directory: ./session_rust
      run: cargo clippy --all-targets --all-features -- -D warnings

    - name: Run tests
      working-directory: ./session_rust
      run: cargo test --verbose

    - name: Build release
      working-directory: ./session_rust
      run: cargo build --release --verbose

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: rust-binary-${{ matrix.os }}-${{ matrix.rust }}
        path: |
          session_rust/target/release/session_rust*
          session_rust/target/release/deps/
