name: Build Session C++

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Debug, Release]

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      working-directory: ./session_cpp
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - name: Build
      working-directory: ./session_cpp
      run: cmake --build build --config ${{ matrix.build_type }}

    - name: Run tests
      working-directory: ./session_cpp
      run: |
        cd build
        ctest --output-on-failure

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: cpp-build-${{ matrix.os }}-${{ matrix.build_type }}
        path: session_cpp/build/
