name: Build Session Python

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.9', '3.13']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      working-directory: ./session_py
      run: |
        python -m pip install --upgrade pip
        pip install build pytest

    - name: Run tests
      working-directory: ./session_py
      shell: bash
      run: |
        if [ -d "tests" ]; then
          python -m pytest tests/ -v
        else
          echo "No tests directory found, skipping tests"
        fi

    - name: Build package
      working-directory: ./session_py
      run: |
        python -m build

    - name: Test import
      working-directory: ./session_py
      run: |
        python -c "from src.session_py import Point, Color; print('Import successful')"

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: python-dist-${{ matrix.os }}-${{ matrix.python-version }}
        path: session_py/dist/
