name: Build and Deploy Documentation

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  # Allow manual triggering
  workflow_dispatch:

jobs:
  documentation:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup Doxygen
      uses: ssciwr/doxygen-install@v1
      with:
        version: "1.9.4"
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # Build C++ Documentation with doxygen-awesome theme
    - name: Build C++ Documentation
      working-directory: ./session_cpp
      run: |
        chmod +x doc.sh
        ./doc.sh

    # Build Python Documentation  
    - name: Install Python documentation dependencies
      working-directory: ./session_py
      run: |
        pip install sphinx sphinx-rtd-theme myst-parser
        # Also install the package itself so autodoc can import it
        pip install -e .
        
    - name: Build Python Documentation
      working-directory: ./session_py
      run: |
        chmod +x doc.sh
        ./doc.sh

    # Build Rust Documentation
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      
    - name: Build Rust Documentation
      working-directory: ./session_rust
      run: |
        cargo doc --no-deps --document-private-items
        # Copy to standard docs_output location for consistency
        mkdir -p docs_output
        cp -r target/doc docs_output/html

    # Upload all documentation artifacts
    - name: Upload C++ Documentation
      uses: actions/upload-artifact@v4
      with:
        name: cpp-docs
        path: session_cpp/docs_output/

    - name: Upload Python Documentation
      uses: actions/upload-artifact@v4
      with:
        name: python-docs  
        path: session_py/docs_output/

    - name: Upload Rust Documentation
      uses: actions/upload-artifact@v4
      with:
        name: rust-docs
        path: session_rust/docs_output/

    # Build combined documentation using session_docs
    - name: Build Combined Documentation
      working-directory: ./session_docs
      run: |
        chmod +x build_docs.sh
        ./build_docs.sh

    - name: Upload Combined Documentation
      uses: actions/upload-artifact@v4
      with:
        name: all-documentation
        path: session_docs/combined_docs/
        
    # Deploy to GitHub Pages (only on main branch)
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./session_docs/combined_docs
        publish_branch: docs
        force_orphan: true
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
