name: Deploy Documentation

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  # Trigger after the build-docs workflow completes
  workflow_run:
    workflows: ["Build Documentation"]
    types:
      - completed

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4

    # Download the documentation artifacts from build-docs workflow
    - name: Download documentation artifacts
      uses: actions/download-artifact@v4
      with:
        name: all-documentation
        path: docs_unified

    # Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs_unified
        publish_branch: docs
